mysql:
  Dbhost: 127.0.0.1
  Dbport: 3306
  Dbuser: root
  Dbpassword: Ly05985481282
  Dbdatabase: todolist

service:
  AppMode: debug
  HttpPort: ":8080"

redis:
  redis_host: 127.0.0.1
  redis_port: 6379
  redis_password: ""
  redisDbName: 2